version: "3.5"
services:
  app:
    container_name: app
    env_file:
      - .env.prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: bash -c "yarn setup && yarn start:prod"
    restart: unless-stopped
    ports:
      - "${PORT}:3000"
    volumes:
      - .env.prod:/.env
      - ./src:/src
      - ./package.json:/package.json
      - ./yarn.lock:/yarn.lock
    depends_on:
      - mysql

  mysql:
    image: mysql
    container_name: mysql
    env_file:
      - .env.prod
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_volume:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "${MYSQL_PORT}:3306"
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    env_file:
      - .env.prod
    environment:
      PMA_HOST: mysql
    ports:
      - "${PHPMYADMIN_PORT}:80"
    restart: unless-stopped
    depends_on:
      - mysql

volumes:
  # default directory on Ubuntu: /var/lib/docker/volumes
  mysql_volume:
    name: node-base-mysql-production-volume
