export const CONFIGURATION_KEYS = {
  PORT: 'PORT',
  ENVIRONMENT: 'ENVIROMENT',
  API_URL: 'API_URL',
  // database
  DATABASE_TYPE: 'DATABASE_TYPE',
  DATABASE_HOST: 'DATABASE_HOST',
  MYSQL_DATABASE: 'MYSQL_DATABASE',
  MYSQL_USER: 'MYSQL_USER',
  MYSQL_PASSWORD: 'MYSQL_PASSWORD',
  MYSQL_PORT: 'MYSQL_PORT',
  SECRET: 'SECRET',
  TOKEN_EXPIRES: 'TOKEN_EXPIRES',
  REFRESH_TOKEN_EXPIRES: 'REFRESH_TOKEN_EXPIRES',
};